@startuml

Object Main
Object Game
Object Player
Object Stages
Object Equipment
Object Interactions
Object Monsters
Object Characters
Object FileIO



Main -- Game
Main -- FileIO
Game *-- Stages : 2
Game *-- Player : 1
Player *-- Characters : 2-5
Player *-- Equipment
Stages -- Player
Stages *-- Monsters
Stages *-- Interactions

@enduml